version: '3'

services:
  webserver:
    build: ./
    image: node_server:1.0
    container_name: node_server
    ports:
      - 3000:3000
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - '3306:3306'
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - .docker/data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=google_meet
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
    networks:
      - app-network

  redis:
    image: redis:alpine3.14
    container_name: redis
    volumes:
      - .docker/data/redis:/data
    ports:
      - 6379:6379
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=0
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=app
      - PMA_PASSWORD=secret
    ports:
      - '81:80'
    volumes:
      - /sessions
    networks:
      - app-network

networks:
  app-network:
    driver: bridge